### ISSUE TITLE
Unable to connect to SQL Server!

### ISSUE THREAD

**Issue by tacul** [1971Merlin/Kaseya-NOC#1]
Hi, this tool is great!! I Could not connect with Windows Authentication, is that possible?

**Comment by tacul** [comment]
now i have this problem:

![image](https://cloud.githubusercontent.com/assets/6086049/7843611/16d197dc-0481-11e5-8ece-5e3aef3736d3.png)

**Comment by 1971Merlin** [comment]
Invalid object name suggests you're not connecting to the database correctly, or are missing the correct components on your web server machine.

For the latest version of XAMPP, there is a new procedure as follows, because XAMPP is now built with a newer version of PHP.

install xampp 5.6.3 (php 5.6.3 / apache 2.4.10) vC11 x86
install visual C++ 2012 runtime (x86)
install ms odbc driver 11 for sql server
drop in php_sqlsrv_56.dll (add to php\ext folder and edit php.ini as per previous release notes).

**Comment by 1971Merlin** [comment]
Closing issue - no response form OP.
